name: flutter_splendid_ble
description: A comprehensive Flutter plugin for interacting with Bluetooth Low Energy (BLE) devices.
version: 0.16.0
homepage: https://github.com/Toglefritz/flutter_splendid_ble
repository: https://github.com/Toglefritz/flutter_splendid_ble

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Provides Lint rules for Flutter and Dart
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.splendidendeavors.flutter_splendid_ble
        pluginClass: FlutterSplendidBlePlugin
      ios:
        pluginClass: FlutterSplendidBlePlugin
      macos:
        pluginClass: FlutterSplendidBlePlugin